### GET all projects
GET http://localhost:8080/projects/

###

### Add a new User
POST http://localhost:8080/users/
Content-type: application/json

{
  "login": "User 1",
  "email": "test@mail.com"
}
> {%
client.global.set("creatorId", response.body.id);
 %}

### Post a new project
POST http://localhost:8080/projects/
Content-type: application/json

{
  "name": "Project 3",
  "description": "This is project 3",
  "creatorId": {{creatorId}}
}

###

### Add a user in a existing project

PATCH http://localhost:8080/projects/1/users
Content-Type: application/json

['']
